#!/usr/bin/env python3
"""Generate grid_tariff_costs.sql from ERSE_TAR_Complete_2026.xlsx (TAR_Lookup sheet)."""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXCEL_PATH = REPO_ROOT / "ERSE_TAR_Complete_2026.xlsx"
OUTPUT_PATH = REPO_ROOT / "backend" / "app" / "db" / "seeds" / "grid_tariff_costs.sql"


def main() -> int:
    if not EXCEL_PATH.exists():
        print(f"Excel file not found: {EXCEL_PATH}", file=sys.stderr)
        print("Place ERSE_TAR_Complete_2026.xlsx in the project root and run again.", file=sys.stderr)
        return 1

    try:
        import openpyxl
    except ImportError:
        print("Install openpyxl: pip install openpyxl", file=sys.stderr)
        return 1

    wb = openpyxl.load_workbook(EXCEL_PATH, read_only=True, data_only=True)
    ws = wb["TAR_Lookup"]
    rows = list(ws.iter_rows(min_row=2, values_only=True))
    wb.close()

    # Columns: tariff_type, voltage_level, season, day_of_week, slot_name, start_time, end_time, TAR_EUR_per_kWh
    values = []
    for r in rows:
        if not r or len(r) < 8:
            continue
        tariff_type, voltage_level, season, day_of_week, slot_name, start_time, end_time, tar = r[:8]
        if not tariff_type or tar is None:
            continue
        # Normalize
        st = str(start_time) if start_time is not None else "00:00"
        et = str(end_time) if end_time is not None else "24:00"
        if ":" not in st:
            st = "00:00"
        if ":" not in et:
            et = "24:00"
        try:
            tar_val = float(tar)
        except (TypeError, ValueError):
            continue
        values.append(
            f"('{tariff_type}', '{voltage_level}', '{season}', '{day_of_week}', "
            f"'{slot_name}', '{st}', '{et}', {tar_val})"
        )

    sql = f"""-- Grid tariff costs (TAR) from ERSE_TAR_Complete_2026.xlsx
-- Generated by scripts/generate_grid_tariff_costs.py

INSERT OR IGNORE INTO grid_tariff_costs (
    tariff_type, voltage_level, season, day_of_week, slot_name,
    start_time, end_time, grid_access_eur_kwh
) VALUES
"""
    sql += ",\n".join(values) + "\n"

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(values)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
